services:
  database:
    build:
      context: ./bin
      dockerfile: Dockerfile
    container_name: application_users
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - postgres_init_data:/var/lib/postgresql/data
volumes:
  postgres_init_data: